### ISSUE TITLE
Serving dagu behind reverse proxy on subpath

### ISSUE THREAD

**Issue by agajic-modoolar** [dagu-org/dagu#575]
Hello,

Is there a way configure dagu to run on subpath? I would like to configure Nginx to redirect subpath traffic to dagu, eg `https://example.com/dagu`, but if i do that, dagu expects to find assets bundle at `https://example.com/assets/bundle.js`, which is not correct.

**Comment by yohamta** [comment]
Hello, 

currently it is not possible as Dagu only has an option for host name. We should add new environment variable option `DAGU_BASE_URL`.
