### ISSUE TITLE
Add environment variable `DAGU_BASE_URL`

### ISSUE THREAD

**Issue by yohamta** [dagu-org/dagu#576]
Currently, Dagu is unable to run behind a proxy. To address this, we need to introduce a new environment variable that allows specifying a different base URL for Dagu.

New environment variable: `DAGU_BASE_URL`

**Additional Context**
- #575
- https://airflow.apache.org/docs/apache-airflow/stable/howto/run-behind-proxy.html

**Comment by chrishoage** [comment]
Is this actively being worked on?

I am currently evaluating this tool for solving some problems, and I require it to exist behind a reverse proxy. 

If no one is actively working on this issue I may pick it up if my evaluation ends up with me accepting this tool. I just don't want to double up work if somebody is already actively solving this problem.  

If you are seeking third party support for implementing this feature do you have any suggestions on the approach that you would deem most acceptable?

**Comment by yohamta** [comment]
@chrishoage Yes, that would be great, thanks! :) I believe no one is actively working on this at the moment.

Here are the files that need modification:

1. **config.go**: [config.go](https://github.com/dagu-org/dagu/blob/main/internal/config/config.go#L33)
   - Add a configuration variable, `DAGU_BASE_URL`.

2. **templates.go**: [templates.go](https://github.com/dagu-org/dagu/blob/855e75d83bf1e618693a1cec084b380861a5ea87/internal/frontend/server/templates.go#L81-L83)
   - Modify the `apiURL` function to return `path.Join(cfg.BaseURL, cfg.APIBaseURL)` instead of `cfg.APIBaseURL`.

Thanks again for considering this! Let me know if you need any more details or help.
