### ISSUE TITLE
Status Dashboard Page fetch http 422 with DAG List API

### ISSUE THREAD

**Issue by Arvintian** [dagu-org/dagu#675]
Fronted not adapt with https://github.com/dagu-org/dagu/issues/653

**Comment by samuelgodoy** [comment]
The Dashboard for version 1.14.3 is not working on Linux Arch64 (Raspbian).

![dashboard](https://github.com/user-attachments/assets/dcae8209-2fec-4f17-9271-c5a7cc447287)
