### ISSUE TITLE
The arg start-all is not working at version 1.14.3

### ISSUE THREAD

**Issue by samuelgodoy** [dagu-org/dagu#679]
The start-all argument is not working in version 1.14.3 on Linux Arch64 (Raspbian), which is the same issue as #461

This command bellow works

`dagu server start --config /home/ry/.config/dagu/admin.yaml & sleep 1 && dagu scheduler`

**Comment by yohamta** [comment]
Hey @samuelgodoy , thanks for letting us know about this issue. I gave the `start-all` command a try on my local machine, but I couldn't recreate the problem you described. I might be missing something here. Would you mind giving me a bit more detail about what's going wrong? That would really help me understand the situation better. Let me know if you need anything else!

**Comment by yohamta** [comment]
Apologies for the delayed response. This issue should be resolved now. Please feel free to reopen it if you encounter any further problems.
