### ISSUE TITLE
If there are multiple dags pagas, sorting works only for the current page. v1.14.6

### ISSUE THREAD

**Issue by kamandir** [dagu-org/dagu#700]
Hey!

I have many dags, which result in multiple pages. If I want to sort by status or time, sorting only takes care of the current page. This is wrong. ;) My Expectation is to have ALL my dags sorted, no matter how many pages I have.

Thanks!

**Comment by yohamta** [comment]
Would you mind sharing how many DAGs you have, and what makes each of them unique?

**Comment by yohamta** [comment]
Let's add a `perPage` configuration to resolve this issue quickly. We can add status sorting afterward.

**Comment by yohamta** [comment]
This issue should be resolved in version 1.14.7. Could you please try updating and let me know if it breaks anything :)

**Comment by kamandir** [comment]
it is better now! thanks a lot!

**Comment by ghansham** [comment]
We solved the core issue of global sorting based on column value..
@kriyanshii solved it... we will try to share it.
