### ISSUE TITLE
Debug DAGU in vs code

### ISSUE THREAD

**Issue by kacamific** [dagu-org/dagu#760]
HI,

I am quite sure that this is a basic question, but I would really appreciate some help. While starting the Server in debug mode I am able to reach some breakpoints, I am not able to reach code in the agent.go: ex: [logger.Info(ctx, "DAG execution started", "reqId", a.requestID, "name", a.dag.Name, "params", a.dag.Params) (line 198)](https://github.com/dagu-org/dagu/blob/6a9ff214f112bfa3e8f0f51a2d9974e0dca21407/internal/agent/agent.go#L195).

Any advice for me?

Kind regards,
K

**Comment by yohamta** [comment]
Hi @kacamific, since DAG execution from the server runs as a separate process, breakpoints won't be triggered. For debugging DAGs, run `dagu start <DAG>` command with debug mode in your VSCode.

**Comment by kacamific** [comment]
Thank you for your swift response, 

It would really help if you share the launch.json configuration.
Nonetheless, thanks for clarifying!

Br,

**Comment by yohamta** [comment]
You're welcome. The `.launch.json` setting for `dagu start` can be found here. You can just update the `args` if you want to debug another DAG file.

https://github.com/dagu-org/dagu/blob/6a9ff214f112bfa3e8f0f51a2d9974e0dca21407/.vscode/launch.json#L30-L41

**Comment by kacamific** [comment]
Amazing support! 

Thank you!
